# Generated by Django 5.1.3 on 2024-12-02 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                ("email_address", models.EmailField(max_length=254)),
                ("school_name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="StudentUser",
            fields=[
                (
                    "baseuser_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="users.baseuser",
                    ),
                ),
            ],
            bases=("users.baseuser",),
        ),
        migrations.CreateModel(
            name="TeacherUser",
            fields=[
                (
                    "baseuser_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="users.baseuser",
                    ),
                ),
            ],
            bases=("users.baseuser",),
        ),
    ]
